server:
  servlet:
    context-path: /
  port: 8081

spring:
  application:
    name: blogpost-service

# show sql in log
  jpa:
    show-sql: true
    properties:
      hibernate:
        hbm2ddl.auto: none
        format_sql: true
        use_sql_comments: true
  profiles:
    active: dev
