spring:
  application:
    name: blogpost-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: test
    password: test
  config:
    import: classpath:.s3.secret.env[.properties]
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000

file:
  operation:
    aws:
      s3:
        accessKey: ${AWS_S3_ACCESS_KEY}
        secretKey: ${AWS_S3_SECRET_KEY}
        region: ${AWS_S3_REGION}

springdoc:
  api-docs:
    path: /blogpost-service/v3/api-docs
  swagger-ui:
    path: /blogpost-service/swagger-ui.html

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    org.springframework.security: trace

kafka:
  producerBootstrapServer: localhost:9093
  consumerBootstrapServer: localhost:9093
