version: "3.7"
services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  rabbitmq:
    image: "rabbitmq:latest"
    environment:
      - "RABBITMQ_DEFAULT_PASS=secret"
      - "RABBITMQ_DEFAULT_USER=myuser"
    ports:
      - "5672"
  redis:
    container_name: "redis"
    hostname: "redis"
    image: "redis:6.2"
    ports:
      - "6379:6379"
volumes:
  db-data:
  pgadmin-data:
