spring:
  application:
    name: search-service
  jackson:
    serialization:
      fail-on-empty-beans: false

elasticsearch:
  url: ${ELASTICSEARCH_URL}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${CONTENTFARM_EUREKA_URL}

kafka:
  producerBootstrapServer: ${KAFKA_URL}
  consumerBootstrapServer: ${KAFKA_URL}