spring:
  application:
    name: search-service
  jackson:
    serialization:
      fail-on-empty-beans: false

elasticsearch:
  url: "localhost:9200"

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

kafka:
  producerBootstrapServer: localhost:9093
  consumerBootstrapServer: localhost:9093
