spring:
  application:
    name: search-service
  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
