spring:
  application:
    name: multimedia-service

springdoc:
  api-docs:
    path: /multimedia-service/v3/api-docs
  swagger-ui:
    path: /multimedia-service/swagger-ui.html

file:
  operation:
    aws:
      s3:
        accessKey: ${AWS_S3_ACCESS_KEY}
        secretKey: ${AWS_S3_SECRET_KEY}
        region: ${AWS_S3_REGION}

eureka:
  client:
    service-url:
      defaultZone: ${CONTENTFARM_EUREKA_URL}
    register-with-eureka: true
    fetch-registry: true