server:
  port: 8080
spring:
  application:
    name: contentfarm-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:9000
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - '*'
            allowed-methods:
              - GET
              - POST
              - DELETE
      discovery:
        locator:
          enabled: true
      routes:
        - id: blogpost-service
          uri: lb://blogpost-service
          predicates:
            - Path=/blogpost/**
        - id: multimedia-service
          uri: lb://multimedia-service
          predicates:
            - Path=/multimedia/**
        - id: search-service
          uri: lb://search-service
          predicates:
            - Path=/search/**
        - id: admin-service
          uri: lb://admin-service
          predicates:
            - Path=/admin/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  enable-native-support: true
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    config-url: /v3/api-docs/swagger-config
    urls:
      - url: /v3/api-docs
        name: API Gateway Service
      - url: /blogpost-service/v3/api-docs
        name: Blog Service
      - url: /multimedia-service/v3/api-docs
        name: Multimedia Service

logging:
  level:
    org.springframework.cloud.gateway: trace
    org.springframework.security: trace
